language: perl
script: HARNESS_IS_VERBOSE=1 prove -Iinc -Ilib t
install:
  - cpanm "Exporter::Tiny" "Hash::FieldHash" "MooseX::Types::Moose" "Test::Fatal" "Test::Requires" "Types::Standard"
perl:
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.26"
matrix:
  include:
    # More minimal version
    - perl: "5.8"
      install:
        - cpanm "Exporter::Tiny" "Hash::FieldHash"
      env:
        - BUILD_NAME=Minimal
    # XS
    - perl: "5.26"
      install:
        - cpanm "Exporter::Tiny" "Hash::FieldHash" "Type::Tiny::XS" "Test::Fatal" "Test::Requires" "Types::Standard"
        - BUILD_NAME=XS
